version: "3.8"
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: yanatori
      POSTGRES_PASSWORD: yanatori
      POSTGRES_DB: nostalgic-moments-db
    restart: always
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: nostalgic-moments-db